#! /bin/sh
# Created by: Elias Mote and Ryan Moeller

VENV=problem1/.venv27
[ -d "${VENV}" ] || {
	echo 'Please run "make" first'
	exit
}
. ${VENV}/bin/activate

eval `opam env --set-switch`
which dune 2>/dev/null >/dev/null || {
	echo 'Please use "make run" or install dune with opam'
	exit
}

choice="0"
while [ "$choice" != "3" ]
do
	echo 'Please input the problem number (1 or 2) or 3 to quit.'
	read choice
	if [ "$choice" = "1" ]
	then
		cd problem1
		python ./project_1_prob_1.py
		cd - >/dev/null
	elif [ "$choice" = "2" ]
	then
		cd problem2
		/bin/echo -n "Enter a positive integer: "
		read k
		/bin/echo -n "Enter a set of digits (0-9, space separated, one line): "
		read digits
		dune exec bin/main.exe -- smallest-multiple $k $digits
		cd - >/dev/null
	elif [ "$choice" = "3" ]
	then
		break
	else
		echo 'That choice is not available.'
	fi
done

deactivate
